### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by dwdrajesh** [mridulghanshala/LeetRepeet#20]
Hi, is the extension still available? seems like this link does not work anymore: 
https://chrome.google.com/webstore/detail/leet-repeet/odpadfgphijikfmdaefmhpjdebahnmde

**Comment by bryantp** [comment]
The extension was removed from the store for violating their store policy. What specifically, I am not sure.

**Comment by dwdrajesh** [comment]
Hi, thanks. Is there any other way to install it now then ?

**Comment by rajat844** [comment]
> @dwdrajesh I've built it from source code, and imported its crx file in chrome dev mode. It works for me

How did u do that?? can u tell me the steps

**Comment by stonecharioteer** [comment]
@rajat844 Use this http://www.dre.vanderbilt.edu/~schmidt/android/android-4.0/external/chromium/chrome/common/extensions/docs/packaging.html

**Comment by dwdrajesh** [comment]
> @rajat844 Use this http://www.dre.vanderbilt.edu/~schmidt/android/android-4.0/external/chromium/chrome/common/extensions/docs/packaging.html

Hi , Do you have steps on how to download the source and package it from beginning? Sorry I am not that familiar with this.

**Comment by rajat844** [comment]
> > @rajat844 Use this http://www.dre.vanderbilt.edu/~schmidt/android/android-4.0/external/chromium/chrome/common/extensions/docs/packaging.html
> 
> Hi , Do you have steps on how to download the source and package it from beginning? Sorry I am not that familiar with this.

while packing extension it says manifest file missing on unreadable. Acc StackOverflow it is named correctly. How can I resolve it ?

**Comment by mridulghanshala** [comment]
hey i have reapplied with the necessary code changes according to google policy. You should see it soon.
