### ISSUE TITLE
Chrome Extension Link isn't working

### ISSUE THREAD

**Issue by biswajitdasme** [mridulghanshala/LeetRepeet#21]
Sorry to inform chrome extension link isn't working. Probably It was removed from Chrome Web Store because of a violation of Google policy.

**Comment by mridulghanshala** [comment]
hey just saw this. Let me take a look

**Comment by Frank-22** [comment]
Any updates?

**Comment by shy-tan** [comment]
Still not working

**Comment by mridulghanshala** [comment]
hey i have applied to republish sorry about the delay.
